apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http-server
  template:
    metadata:
      labels:
        app: simple-http-server
    spec:
      containers:
      - name: simple-http-server
        image: registry.local:9001/public/hello-world:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-http-server-service
spec:
  selector:
    app: simple-http-server
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32666
  type: NodePort
